name: SonarQube Analysis

on:
  push:
    branches:
      - main    # Run for push events to the 'main' branch
  pull_request:
    branches:
      - main    # Run for pull requests targeting the 'main' branch

jobs:
  sonarQube:
    name: Run SonarQube Analysis
    runs-on: ubuntu-latest    # Choose an Ubuntu environment (other options are available)
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: 'x64'
        overwrite-settings: true

    - name: Build with Maven
      run: mvn clean install
        
    - name: Install dependencies
      run: mvn install
    
    - name: SonarQube analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=my-intellij-project \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=$SONAR_TOKEN
